### ISSUE TITLE
Testing upload within graphql-ruby

### ISSUE THREAD

**Issue by guyzmo** [jetruby/apollo_upload_server-ruby#16]
Hi :wave:

I'm trying to write tests for my rmosolgo/graphql-ruby project, and I don't know how I can prepare a file to be passed as `variables` to `MySchema.execute` within a rspec example, so I can test my upload mutation.

I tried looking at the specs of this project, but had no luck.

I also asked there: rmosolgo/graphql-ruby#2146 with some more details.

**Comment by fuelen** [comment]
Hi @guyzmo 
Try this `Rack::Test::UploadedFile.new("path/to/file.ext", "mime/type")`

**Comment by guyzmo** [comment]
it works, thanks 🙌
