### ISSUE TITLE
Not compatible with graphql gem >= v1.10.0

### ISSUE THREAD

**Issue by ralph** [jetruby/apollo_upload_server-ruby#24]
Hi, thank you for creating this file uploading type. Unfortunately, it does not seem to work with current versions of the graphql Ruby gem. I'm seing this stacktrace when I try to update graphql:

```
rails_1        | ArgumentError: Can't add legacy type: Upload (GraphQL::ScalarType)
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1767:in `add_type'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1811:in `block in add_type'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1808:in `each'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1808:in `add_type'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1811:in `block in add_type'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1808:in `each'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1808:in `add_type'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1803:in `block (2 levels) in add_type'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1800:in `each'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1800:in `block in add_type'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1796:in `each'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1796:in `add_type'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1673:in `block in add_type_and_traverse'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1673:in `each'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:1673:in `add_type_and_traverse'
rails_1        | /bundle/ruby/2.6.0/gems/graphql-1.10.2/lib/graphql/schema.rb:972:in `mutation'
```

**Comment by 00dav00** [comment]
Experiencing the same, any idea on how to fix this?

**Comment by ralph** [comment]
Unfortunately not, I did not dig deeper, as updating to `1.10` is not a top priority for us now. I guess `apollo_upload_server-ruby` needs to be refactored to be compatible with `1.10`, but I did not look at the details or whether this is a big or a small effort.

**Comment by 00dav00** [comment]
@ralph this [commit](https://github.com/jetruby/apollo_upload_server-ruby/commit/a7180804df7a21f3a44e2c8f0bfec2a072f7673a) fixes the problem, make sure your repo is using a version that includes it.

It seems like the Upload scalar using  `GraphQL::ScalarType.define` is not longer supported in gql 1.10 but the one inheriting from `GraphQL::Schema::Scalar` is.

**Comment by ralph** [comment]
Can't confirm, I've tried installing `apollo_upload_server-ruby` version `2.0.1`, same error. 🤷‍♂

**Comment by ralph** [comment]
Hi, I'm sorry, the latest version works totally fine. My problem was that I installed a monkey patch in an initializer to make `apollo_upload_server-ruby` work with ActiveStorage, and totally forgot about it. The monkey patch was still using the old syntax and can be found here:

https://github.com/jetruby/apollo_upload_server-ruby/issues/10#issuecomment-433772885

I updated the patch to work with the latest version:

`config/initializers/apollo_upload_server_active_storage_patch.rb`

```
# frozen_string_literal: true

module ApolloUploadServer
  class GraphQLDataBuilder
    def assign_file(field, splited_path, file)
      if field.is_a? Hash
        field.merge!(splited_path.last => file)
      elsif field.is_a? Array
        field[splited_path.last.to_i] = file
      end
    end
  end

  remove_const :Upload
  class Upload < GraphQL::Schema::Scalar
    graphql_name "Upload"

    def self.coerce_input(value, _ctx)
      value
    end

    def self.coerse_result(value, _ctx)
      return if value.nil?

      def value.as_json(options = nil)
        instance_values.except('tempfile').as_json(options)
      end
      value
    end
  end
end
```
