### ISSUE TITLE
Support for Rails <5.0?

### ISSUE THREAD

**Issue by tiffwu** [jetruby/apollo_upload_server-ruby#3]
My application is on 4.2.8 and we won't be upgrading any time in the near future -- does this gem have to have a hard 5.0+ dependency, or can it be loosened?

**Comment by fuelen** [comment]
Hi @tiffwu!
I think there is no strong requirement to have 5.0+ version.
We've set to 5.0 because we had tested on it.
Try to set 4.2.8. PRs with changes are welcome :)
