### ISSUE TITLE
How to integrate with shrine?

### ISSUE THREAD

**Issue by bravemaster619** [jetruby/apollo_upload_server-ruby#31]
I don't understand `rspec` in the source code. Any help would be appreciated.

**Comment by fuelen** [comment]
What actually do you want to test? What have you tried so far?

**Comment by bravemaster619** [comment]
Hi @fuelen , I'm using `shrine` and `apollo_upload_server-ruby` to implement image uploading. Client request is coming from `apollo-upload-client` with `React Native`.

**save_profile_input.rb**
```ruby
module Types
  class SaveProfileInput < Types::BaseInputObject
    argument :summary, String, required: true
    argument :favorite_food, String, required: true
    argument :hated_food, String, required: true
    argument :profile_image, ApolloUploadServer::Upload, required: false
  end
end
```
**save_profile.rb** (mutation)
```ruby
module Mutations
  class SaveProfile < Mutations::BaseMutation
    include AuthHelper

    graphql_name 'save_profile'

    argument :profile, Types::SaveProfileInput, required: true

    field :user, Types::UserType, null: false

    def resolve(input)
      auth_check
      @user = context[:current_user]
      @profile = input[:profile]
      set_base_info
      set_image
      @user.save!
      { user: @user }
    end

    def set_base_info
      @user[:summary] = @profile[:summary]
      @user[:favorite_food] = @profile[:favorite_food]
      @user[:hated_food] = @profile[:hated_food]
    end

    def set_image
      return unless @profile[:profile_image]
      image = Image.new(image: @profile[:profile_image])
      @user.image = image
    end

  end
end
```

When I send a request to server, it shows following error:
> <ActionController::Parameters {"uri"=>"file:///Users/bravemaster619/Library/Developer/CoreSimulator/Devices/20338FA2-B214-4C8B-96EA-41C8DFC18462/data/Containers/Data/Application/D8B35974-EC03-4560-9D23-46BE0D400DBB/tmp/4CD88824-ABB9-4FEF-A6E3-7F778A873A11.jpg", "name"=>nil, "type"=>"image/jpeg"} permitted: false> is not a valid IO object (it doesn't respond to #read, #eof?, #rewind, #close)

I've been trying to fix this problem by myself for all day long, but no luck.

I tried to refer to rspec in your project but I don't understand it. Please help.

P.S. Why not improving README.md?

**Comment by bravemaster619** [comment]
Dependencies versions are as follows:
```ruby
gem 'apollo_upload_server', '2.0.1'
gem 'shrine', '~>3.0'
```
```
"apollo-upload-client": "^13.0.0"
```
Profile image is created in `React Native` like the following:
```javascript
onChange={(response: ImagePickerResponse) => {
            setUploadImage(new ReactNativeFile({
              uri: response.uri,
              name: response.fileName,
              type: response.type
            }));
          }}
```

**Comment by fuelen** [comment]
Unfortunately, I don't have experience with React Native, so can't say much here.
Could you post all parameters that are sent to the server?
It seems like you don't send a file, but some other object instead.

> coerce_input and coerce_result look important but can't get any doc from anywhere

you can read about custom scalars here -> https://graphql-ruby.org/type_definitions/scalars.html

> P.S. Why not improving README.md? #12

PRs are welcome :)

**Comment by bravemaster619** [comment]
@fuelen Thanks for response. I will check my React Native code, but it's from the [official guide](https://github.com/jaydenseric/apollo-upload-client#examples).

How do you handle image uploading with shrine anyway? In other words, is `SaveProfile#set_image` implemented correctly? Or am I missing something in my code? Assuming if a file is received correctly from client side?

**Comment by fuelen** [comment]
This library is totally independent of `srine`.  You should just get a regular object with uploaded file.

**Comment by bravemaster619** [comment]
I know it's independent of `shrine`. You mentioned about `shrine` here: https://github.com/jetruby/apollo_upload_server-ruby/issues/10#issuecomment-382654285 

I just wanted to know example usage with shrine.

**Comment by bravemaster619** [comment]
Closed due to long inactivity
