### ISSUE TITLE
2.1.1 is Incompatible with Rails 7

### ISSUE THREAD

**Issue by Petercopter** [jetruby/apollo_upload_server-ruby#50]
I was trying to upgrade from 2.1.0 to 2.1.1, and I'm getting this error:

```
Bundler could not find compatible versions for gem "actionpack":
  In snapshot (Gemfile.lock):
    actionpack (>= 7.0.3.1)

  In Gemfile:
    apollo_upload_server (~> 2.1, >= 2.1.1) was resolved to 2.1.1, which depends on
      actionpack (~> 6.1)

    rails (~> 7.0, >= 7.0.2.3) was resolved to 7.0.3.1, which depends on
      actionpack (= 7.0.3.1)

Deleting your Gemfile.lock file and running `bundle install` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Been using 2.1.0 for awhile now with Rails 7, it's working great :D

**Comment by fuelen** [comment]
Seems like related to https://github.com/jetruby/apollo_upload_server-ruby/pull/49

Sorry, I don't use Ruby & Rails for a while, so the only I can do here is to accept a PR with fixes and publish a new release :)

**Comment by pauljacksonrodgers** [comment]
@fuelen I have tried to resolve this in #51, if you wouldn't mind taking a look. Thanks!
