### ISSUE TITLE
recent PR with a breaking change

### ISSUE THREAD

**Issue by codebender** [jetruby/apollo_upload_server-ruby#56]
PR: https://github.com/jetruby/apollo_upload_server-ruby/pull/51

This PR requires the gem users to have rails 7.  Maybe the gem should bump a major version to reflect that breaking change? Are you not longer going to support rails 6.x?

**Comment by fuelen** [comment]
Hi @codebender

These changes were started as an attempt to update dependency with vulnerability. If it is possible to add support for rails 6 without returning vulnerability back, then PR is welcome.

**Comment by oriolgual** [comment]
I think it could be relaxed to Rails 6.1.6, both Rails 7.0.3 (current dependency) and 6.1.6 were released the same day and use rack 2.2.4 (which solves the security issue).
