### ISSUE TITLE
Example of using this gem with Image and Video Management in the Cloud

### ISSUE THREAD

**Issue by nenjamin2405** [jetruby/apollo_upload_server-ruby#7]
First, I really appreciate what you did for graphql-ruby community with this gem. I just wonder how can I actually use this gem with some third party media management platform like Cloudinary after receiving files (images) from the apollo-upload-client.

**Comment by fuelen** [comment]
@nenjamin2405 Hello.
Have you tried to use this library and `apollo-upload-client` without Cloudinary?
You will receive files as usual upload. 

You have to decide on your own what to do with them - save on a local disk, upload to third-party platforms or whatever you want.

**Comment by nenjamin2405** [comment]
Hi @fuelen, I had successfully used your gem together with cloudinary and apollo upload client, thank you so much !

**Comment by fuelen** [comment]
:tada:
